//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesMoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int Id { get; set; }
        public System.DateTime DateRented { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public int Custmer_id { get; set; }
        public int Movie_id { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
